In [1]:
import numpy as np
import pandas as pd


In [2]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [3]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [4]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [5]:
type(data.values)

numpy.ndarray

In [6]:
type(data.index)

pandas.core.indexes.range.RangeIndex

In [7]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index = ['a','b','c','d'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [8]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index = [2, 5, 3, 7])
data

2    0.25
5    0.50
3    0.75
7    1.00
dtype: float64

In [9]:
population_dict = {'California':123, 'Texas': 234, 'New York': 345, 'Florida': 456, 'Illinois': 567}
population = pd.Series(population_dict)
population

California    123
Texas         234
New York      345
Florida       456
Illinois      567
dtype: int64

In [10]:
population['California']

123

In [12]:
population['California':'Illinois']

California    123
Texas         234
New York      345
Florida       456
Illinois      567
dtype: int64

In [13]:
pd.Series({2:'a', 1:'b', 3:'c'})

2    a
1    b
3    c
dtype: object

In [14]:
pd.Series({2:'a', 1:'b', 3:'c'}, index=[3,2])

3    c
2    a
dtype: object

In [15]:
population = pd.Series({'California':123, 'Texas': 234, 'New York': 345, 'Florida': 456, 'Illinois': 567})
area = pd.Series({'California':1230, 'Texas': 2340, 'New York': 3450, 'Florida': 4560, 'Illinois': 5670})


In [16]:
states = pd.DataFrame({'population': population, 'area': area})

In [17]:
states

population  area
California         123  1230
Texas              234  2340
New York           345  3450
Florida            456  4560
Illinois           567  5670

In [18]:
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [19]:
states.columns

Index(['population', 'area'], dtype='object')

In [20]:
population = pd.Series({'C1alifornia':123, 'Texas': 234, 'New York': 345, 'Florida': 456, 'Illinois': 567})
area = pd.Series({'C2alifornia':1230, 'Texas': 2340, 'New York': 3450, 'Florida': 4560, 'Illinois': 5670})
states = pd.DataFrame({'population': population, 'area': area})

In [21]:
states


population    area
C1alifornia       123.0     NaN
C2alifornia         NaN  1230.0
Florida           456.0  4560.0
Illinois          567.0  5670.0
New York          345.0  3450.0
Texas             234.0  2340.0

In [22]:
states['population']

C1alifornia    123.0
C2alifornia      NaN
Florida        456.0
Illinois       567.0
New York       345.0
Texas          234.0
Name: population, dtype: float64

In [23]:
states['area']

C1alifornia       NaN
C2alifornia    1230.0
Florida        4560.0
Illinois       5670.0
New York       3450.0
Texas          2340.0
Name: area, dtype: float64

In [24]:
type(states['area'])

pandas.core.series.Series

In [27]:
pd.DataFrame(population)

0
C1alifornia  123
Texas        234
New York     345
Florida      456
Illinois     567

In [30]:
data = [{'a':1, 'b':3},{'a':10, 'b':30}]
pd.DataFrame(data)

a   b
0   1   3
1  10  30

In [32]:
data = [{'a':1, 'b':3},{'b':10, 'c':30}]
pd.DataFrame(data)

a   b     c
0  1.0   3   NaN
1  NaN  10  30.0

In [35]:
ind = pd.Index([2,3,5,7,11])
ind

Int64Index([2, 3, 5, 7, 11], dtype='int64')

In [38]:
print(ind.size, ind.shape, ind.ndim, ind.dtype)

5 (5,) 1 int64


In [46]:
indA = pd.Index([1, 3, 5, 7, 9])
indB = pd.Index([2, 3, 5, 6, 11])
indA & indB

Int64Index([3, 5], dtype='int64')

In [49]:
import numpy as np
x = np.arange(10)
x[-2]

8

In [52]:
x2 = array([[3,5,2,4,],[7,6,8,8],[1,6,7,7]])
x2[0,1]
x2[2, -1]

7

In [54]:
x = np.arange(10)
x[:5]

array([0, 1, 2, 3, 4])

In [61]:
x2 = array([[3,5,2,4,],[7,6,8,8],[1,6,7,7]])
x2[:2, :3]
x2[:3, ::2]
x2[::-1, ::-1]
x2[0, :]

array([3, 5, 2, 4])

In [63]:
np.arange(0, 9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [66]:
x = np.array([1,2,3])
x[:, np.newaxis]  # x.reshape((3,1))

array([[1],
       [2],
       [3]])

In [77]:
data = pd.Series([0.25,0.5,0.75,1.0], index=['a','b','c','d'])
data['b']
'a' in data
data.keys()
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [88]:
data['a':'c']
type(data['a':'c'])
data[0:2]
data[ (data > 0.3) & (data < 0.8) ]


b    0.50
c    0.75
dtype: float64

In [101]:
data = pd.Series(['a','b','c','d'], index = [1,3,5,7])
data.iloc[1:3]

3    b
5    c
dtype: object

In [105]:
pop = pd.Series({'California':123, 'Texas': 234, 'New York': 345, 'Florida': 456, 'Illinois': 567})
area = pd.Series({'California':1230, 'Texas': 2340, 'New York': 3450, 'Florida': 4560, 'Illinois': 5670})
data = pd.DataFrame({'area': area, 'pop':pop})
data

area  pop
California  1230  123
Texas       2340  234
New York    3450  345
Florida     4560  456
Illinois    5670  567

In [151]:
data['density'] = data['pop'] / data['area']
data
data.iloc[:3, :2]
data.loc['Texas':'Illinois', :'pop']
data.loc[data['pop'] > 300, ['pop', 'area']]

arr = np.arange(0,9).reshape(3,3)
arr[1:3, 0:2]
arr[1:3]
data[data['pop'] > 300]

area  pop  density
New York  3450  345      0.1
Florida   4560  456      0.1
Illinois  5670  567      0.1

In [148]:
import numpy as np
np.random.seed(0)
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)

big_array = np.random.randint(1, 100, size=10000)
%timeit compute_reciprocals(big_array)




15.1 ms ± 188 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [152]:
x = np.arange(1,6)
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [155]:
rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0, 10, 4))
ser
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [167]:
area = pd.Series({'Alaska':172337, 'Texas': 695662, 'California':423967}, name='area')
pop = pd.Series({'California':38332521, 'Texas':26448193, 'New York': 19651127}, name='pop')
pop / area

area.index | pop.index
pop + area

# area.add(pop, fill_value=0)

Alaska               NaN
California    38756488.0
New York             NaN
Texas         27143855.0
dtype: float64

In [176]:
rng = np.random.RandomState(42)

x1= pd.DataFrame(rng.randint(0, 20, (2,2)), columns=list('AB'))
x2 = pd.DataFrame(rng.randint(0, 10, (3,3)), columns=list('ABC'))
x1 + x2
fill = x1.stack().mean()
x1.add(x2, fill_value=fill)

A      B      C
0  13.00  23.00  18.25
1  23.00  12.00  18.25
2  19.25  16.25  15.25

In [246]:
x1 = rng.randint(10, size=(3,4))
x1


ValueError: operands could not be broadcast together with shapes (3,4) (3,2) 

In [243]:
df = pd.DataFrame(x1, columns=list('QRST'))
df - df.iloc[0]
df.subtract(df['R'], axis=0)
halfrow = df.iloc[0]
df - halfrow


type(df.iloc[0])
type(df.iloc[0:1])
df - df.iloc[0:1]

# halfrow


Q    R    S    T
0  0.0  0.0  0.0  0.0
1  NaN  NaN  NaN  NaN
2  NaN  NaN  NaN  NaN